name: wasel_common
description: Common shared package for Wasel Portal system
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase
  supabase_flutter: ^2.5.6
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # HTTP & API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  
  # Storage & Cache
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI & Animations
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  crypto: ^3.0.3
  
  # File handling
  file_picker: ^8.0.0+1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Biometrics
  local_auth: ^2.1.8
  
  # Connectivity
  connectivity_plus: ^6.0.3
  
  # Device info
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code generation
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    
  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/NotoSansArabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansArabic-Medium.ttf
          weight: 500